"""
Myself Manager - Secure file management for i-skill

This module provides secure operations for managing the myself.md file,
ensuring all file operations are handled safely with proper validation.
Content generation is handled by the AI model, this module only manages file operations.

Security Features:
- Path validation to prevent directory traversal
- File permission checks
- Input sanitization and validation
- Secure error handling without exposing sensitive information
"""

import json
import os
from pathlib import Path
from datetime import datetime
from typing import Optional, Dict, Any, List


class SecurityError(Exception):
    """Custom exception for security-related errors"""
    pass


class MyselfManager:
    """Secure manager for myself.md file operations - content generation handled by AI model"""
    
    def __init__(self, user_data_path: str = "./user_data"):
        """Initialize the manager with secure path validation"""
        # Validate and normalize the user data path
        self.user_data_path = self._validate_and_normalize_path(user_data_path)
        self.myself_file = self.user_data_path / "myself.md"
        
        # Ensure user data directory exists with secure permissions
        self._ensure_secure_directory()
    
    def _validate_and_normalize_path(self, path: str) -> Path:
        """Validate and normalize file path to prevent directory traversal"""
        try:
            # Convert to absolute path and resolve any symlinks
            abs_path = Path(path).resolve()
            
            # Ensure path is within current working directory
            cwd = Path.cwd().resolve()
            if not abs_path.is_relative_to(cwd):
                raise SecurityError(f"Path {path} is outside allowed directory")
            
            # Check for directory traversal attempts
            if ".." in str(abs_path.relative_to(cwd)):
                raise SecurityError(f"Directory traversal attempt detected: {path}")
            
            return abs_path
            
        except (ValueError, SecurityError) as e:
            raise SecurityError(f"Invalid path: {path} - {str(e)}")
    
    def _ensure_secure_directory(self):
        """Create directory with secure permissions"""
        try:
            self.user_data_path.mkdir(parents=True, exist_ok=True)
            
            # Set secure permissions (read/write for owner only)
            os.chmod(self.user_data_path, 0o700)
            
        except (OSError, PermissionError) as e:
            raise SecurityError(f"Failed to create secure directory: {str(e)}")
    
    def _validate_file_path(self, file_path: Path) -> bool:
        """Validate that file path is within allowed directory"""
        try:
            # Ensure file is within user_data_path
            if not file_path.resolve().is_relative_to(self.user_data_path.resolve()):
                return False
            
            # Check for common attack patterns
            path_str = str(file_path)
            if any(pattern in path_str for pattern in ['..', '~', '/etc', '/var', '/tmp']):
                return False
                
            return True
            
        except Exception:
            return False
    
    def create_basic_template(self) -> Dict[str, Any]:
        """
        Create a basic myself.md template when i-skill is first activated
        
        Returns:
            Dictionary with operation status and details
        """
        basic_template = """# Assistant Interaction Guide

## User Profile Summary
*Personalized guidance will be generated by AI based on complete conversation analysis*

### Initial Analysis Pending
- **Activation Status**: i-skill activated, awaiting AI analysis
- **Analysis Scope**: AI will analyze both pre-activation and post-activation conversations
- **Content Source**: AI-generated wisdom-level insights or user self-reflection

### Expected Process
1. AI analyzes complete conversation history
2. Generates wisdom-level personalized guidance
3. Content is stored here for persistent context
4. User can also manually edit based on self-understanding

*This guide will evolve with AI analysis and user self-reflection.*"""
        
        return self.create_myself(basic_template)
    
    def update_with_ai_content(self, ai_generated_content: str) -> Dict[str, Any]:
        """
        Update myself.md with AI-generated content
        
        Args:
            ai_generated_content: Content generated by AI model based on conversation analysis
            
        Returns:
            Dictionary with operation status and details
        """
        try:
            # Check if file exists
            if not self.myself_file.exists():
                return {
                    "success": False,
                    "message": "myself.md does not exist. Use create_basic_template() first.",
                    "file_path": str(self.myself_file)
                }
            
            # Validate AI-generated content
            validation_result = self._validate_guidance(ai_generated_content)
            if not validation_result["valid"]:
                return {
                    "success": False,
                    "message": f"AI content validation failed: {validation_result['message']}",
                    "file_path": str(self.myself_file)
                }
            
            # Update the file with AI-generated content
            update_result = self.update_myself(ai_generated_content)
            
            if update_result["success"]:
                self._log_operation("ai_update", f"Updated with AI-generated content ({len(ai_generated_content)} characters)")
            
            return update_result
            
        except Exception as e:
            return {
                "success": False,
                "message": f"AI content update failed: {str(e)}",
                "file_path": str(self.myself_file)
            }
    
    def create_myself(self, guidance_content: str) -> Dict[str, Any]:
        """
        Securely create myself.md file with personalized guidance
        
        Args:
            guidance_content: Personalized guidance content in markdown format
            
        Returns:
            Dictionary with operation status and details
        """
        try:
            # Validate file path security
            if not self._validate_file_path(self.myself_file):
                return {
                    "success": False,
                    "message": "Security violation: Invalid file path",
                    "file_path": str(self.myself_file)
                }
            
            # Validate guidance content
            validation_result = self._validate_guidance(guidance_content)
            if not validation_result["valid"]:
                return {
                    "success": False,
                    "message": f"Guidance validation failed: {validation_result['message']}",
                    "file_path": str(self.myself_file)
                }
            
            # Create the file with secure write
            with open(self.myself_file, 'w', encoding='utf-8') as f:
                f.write(guidance_content)
            
            # Set secure file permissions
            os.chmod(self.myself_file, 0o600)
            
            # Log the creation
            self._log_operation("create", f"Created myself.md with {len(guidance_content)} characters")
            
            return {
                "success": True,
                "message": "myself.md created successfully",
                "file_path": str(self.myself_file),
                "content_length": len(guidance_content)
            }
            
        except (OSError, PermissionError) as e:
            return {
                "success": False,
                "message": "File operation failed due to permission issues",
                "file_path": str(self.myself_file)
            }
        except Exception as e:
            return {
                "success": False,
                "message": "Failed to create myself.md due to internal error",
                "file_path": str(self.myself_file)
            }
    
    def read_myself(self) -> Dict[str, Any]:
        """
        Securely read myself.md file content
        
        Returns:
            Dictionary with operation status and file content
        """
        try:
            if not self.myself_file.exists():
                return {
                    "success": False,
                    "message": "myself.md file does not exist",
                    "file_path": str(self.myself_file),
                    "content": ""
                }
            
            # Read file with secure handling
            with open(self.myself_file, 'r', encoding='utf-8') as f:
                content = f.read()
            
            # Log the read operation
            self._log_operation("read", f"Read myself.md ({len(content)} characters)")
            
            return {
                "success": True,
                "message": "myself.md read successfully",
                "file_path": str(self.myself_file),
                "content": content,
                "content_length": len(content)
            }
            
        except Exception as e:
            return {
                "success": False,
                "message": f"Failed to read myself.md: {str(e)}",
                "file_path": str(self.myself_file),
                "content": ""
            }
    
    def update_myself(self, new_guidance: str) -> Dict[str, Any]:
        """
        Securely update myself.md file with new guidance
        
        Args:
            new_guidance: Updated personalized guidance content
            
        Returns:
            Dictionary with operation status and details
        """
        try:
            # Check if file exists
            if not self.myself_file.exists():
                return {
                    "success": False,
                    "message": "myself.md does not exist. Use create_myself() first.",
                    "file_path": str(self.myself_file)
                }
            
            # Validate new guidance content
            validation_result = self._validate_guidance(new_guidance)
            if not validation_result["valid"]:
                return {
                    "success": False,
                    "message": f"Guidance validation failed: {validation_result['message']}",
                    "file_path": str(self.myself_file)
                }
            
            # Backup existing content (optional)
            backup_content = self.read_myself()["content"] if self.myself_file.exists() else ""
            
            # Update the file
            with open(self.myself_file, 'w', encoding='utf-8') as f:
                f.write(new_guidance)
            
            # Log the update
            self._log_operation("update", f"Updated myself.md ({len(new_guidance)} characters)")
            
            return {
                "success": True,
                "message": "myself.md updated successfully",
                "file_path": str(self.myself_file),
                "content_length": len(new_guidance),
                "previous_content_length": len(backup_content) if backup_content else 0
            }
            
        except Exception as e:
            return {
                "success": False,
                "message": f"Failed to update myself.md: {str(e)}",
                "file_path": str(self.myself_file)
            }
    
    def delete_myself(self) -> Dict[str, Any]:
        """
        Securely delete myself.md file
        
        Returns:
            Dictionary with operation status
        """
        try:
            if not self.myself_file.exists():
                return {
                    "success": False,
                    "message": "myself.md does not exist",
                    "file_path": str(self.myself_file)
                }
            
            # Backup content before deletion (optional)
            backup_content = self.read_myself()["content"]
            
            # Delete the file
            self.myself_file.unlink()
            
            # Log the deletion
            self._log_operation("delete", f"Deleted myself.md")
            
            return {
                "success": True,
                "message": "myself.md deleted successfully",
                "file_path": str(self.myself_file),
                "previous_content_length": len(backup_content)
            }
            
        except Exception as e:
            return {
                "success": False,
                "message": f"Failed to delete myself.md: {str(e)}",
                "file_path": str(self.myself_file)
            }
    
    def get_file_info(self) -> Dict[str, Any]:
        """
        Get information about myself.md file
        
        Returns:
            Dictionary with file information
        """
        try:
            if not self.myself_file.exists():
                return {
                    "exists": False,
                    "file_path": str(self.myself_file),
                    "message": "File does not exist"
                }
            
            stat = self.myself_file.stat()
            content = self.read_myself()
            
            return {
                "exists": True,
                "file_path": str(self.myself_file),
                "file_size": stat.st_size,
                "created_time": datetime.fromtimestamp(stat.st_ctime).isoformat(),
                "modified_time": datetime.fromtimestamp(stat.st_mtime).isoformat(),
                "content_length": content.get("content_length", 0) if content["success"] else 0,
                "message": "File information retrieved successfully"
            }
            
        except Exception as e:
            return {
                "exists": False,
                "file_path": str(self.myself_file),
                "message": f"Failed to get file info: {str(e)}"
            }
    
    def _validate_guidance(self, content: str) -> Dict[str, Any]:
        """
        Validate guidance content for security and quality
        
        Args:
            content: Guidance content to validate
            
        Returns:
            Dictionary with validation result
        """
        # Basic validation rules
        if not content or not content.strip():
            return {"valid": False, "message": "Content cannot be empty"}
        
        if len(content) > 50000:  # Limit file size for security
            return {"valid": False, "message": "Content too large (max 50,000 characters)"}
        
        # Check for potentially dangerous patterns
        dangerous_patterns = [
            "<script>", "javascript:", "vbscript:", "onload=", "onerror="
        ]
        
        for pattern in dangerous_patterns:
            if pattern.lower() in content.lower():
                return {"valid": False, "message": f"Content contains potentially dangerous pattern: {pattern}"}
        
        # Basic markdown structure check
        if not content.startswith('#'):
            return {"valid": True, "message": "Content validated (warning: missing header)"}
        
        return {"valid": True, "message": "Content validated successfully"}
    
    def _log_operation(self, operation: str, details: str):
        """
        Log file operations for audit trail
        
        Args:
            operation: Type of operation (create, read, update, delete)
            details: Operation details
        """
        log_file = self.user_data_path / "myself_operations.log"
        
        log_entry = {
            "timestamp": datetime.now().isoformat(),
            "operation": operation,
            "details": details,
            "file_path": str(self.myself_file)
        }
        
        try:
            with open(log_file, 'a', encoding='utf-8') as f:
                f.write(json.dumps(log_entry) + '\n')
        except Exception:
            pass  # Logging failure should not break main operations


# Convenience functions for easy usage
def create_basic_template() -> Dict[str, Any]:
    """Convenience function to create basic myself.md template"""
    manager = MyselfManager()
    return manager.create_basic_template()


def create_myself_file(content: str) -> Dict[str, Any]:
    """Convenience function to create myself.md"""
    manager = MyselfManager()
    return manager.create_myself(content)


def read_myself_file() -> Dict[str, Any]:
    """Convenience function to read myself.md"""
    manager = MyselfManager()
    return manager.read_myself()


def update_myself_file(content: str) -> Dict[str, Any]:
    """Convenience function to update myself.md"""
    manager = MyselfManager()
    return manager.update_myself(content)


def update_myself_with_ai_content(ai_generated_content: str) -> Dict[str, Any]:
    """Convenience function to update myself.md with AI-generated content"""
    manager = MyselfManager()
    return manager.update_with_ai_content(ai_generated_content)


def delete_myself_file() -> Dict[str, Any]:
    """Convenience function to delete myself.md"""
    manager = MyselfManager()
    return manager.delete_myself()


def get_myself_file_info() -> Dict[str, Any]:
    """Convenience function to get myself.md info"""
    manager = MyselfManager()
    return manager.get_file_info()


if __name__ == "__main__":
    # Example usage and testing
    manager = MyselfManager()
    
    # Test file info
    info = manager.get_file_info()
    print("File Info:", json.dumps(info, indent=2))
    
    # Test create if file doesn't exist
    if not info["exists"]:
        sample_content = """# Assistant Interaction Guide

## User Profile Summary
*Personalized guidance generated by i-skill*"""
        
        result = manager.create_myself(sample_content)
        print("Create Result:", json.dumps(result, indent=2))